export const policeCodes: Record<string, string> = {
  "0": "Use caution",
  "1": "You are being received poorly / Cannot copy",
  "2": "You are being received clearly / Signal is strong",
  "3": "Stop transmitting",
  "4": "Affirmative / Understood / Message received",
  "5": "Relay message to [person]",
  "6": "Busy / Out at call",
  "7": "Out of service (completely)",
  "8": "In service",
  "9": "Repeat last message",
  "10": "Negative / Fight in progress",
  "11": "Identify frequency / Dispatching too fast",
  "12": "Standby / Visitor(s) present",
  "13": "Advise weather and road conditions",
  "14": "Convoy or escort detail / Suspicious person",
  "15": "Prisoner in custody / Message delivered",
  "16": "Pick up prisoner / Reply to message",
  "17": "Pick up papers / En route",
  "18": "Urgent / Complete present assignment ASAP",
  "19": "Return to station or location",
  "20": "Your location",
  "21": "Call by telephone",
  "22": "Disregard / Cancel last message",
  "23": "Arrived at scene / Stand by until channel clears",
  "24": "Emergency backup / Emergency at station",
  "25": "Report to [person] / Do you have contact with [person]",
  "26": "Detaining suspect / Check auto registration",
  "27": "Request drivers license check",
  "28": "Check registration on vehicle",
  "29": "Request arrests/warrants check",
  "30": "Does not conform to rules or regulations",
  "31": "Crime in progress / in pursuit",
  "32": "Person with gun",
  "33": "Emergency, all units stand by",
  "34": "Open door or window / Riot",
  "35": "Confidential information or open window",
  "36": "Provide current time of day",
  "37": "Identify yourself / suspicious vehicle",
  "38": "Traffic stop",
  "39": "Run with lights and siren",
  "40": "Run silent (no lights or siren)",
  "41": "Begin duty",
  "42": "End duty",
  "43": "Information",
  "44": "Permission to leave patrol",
  "45": "Condition of patient",
  "46": "Motorist assist",
  "47": "Emergency road repair",
  "48": "Traffic control",
  "49": "Traffic light out",
  "50": "Officer welfare check / under influence of drugs",
  "51": "Tow truck needed / under influence of alcohol",
  "52": "Ambulance needed",
  "53": "Road blocked / Man down",
  "54": "Possible fatality",
  "55": "Intoxicated driver",
  "56": "Intoxicated pedestrian / Suicide",
  "57": "Hit and run accident / Missing person",
  "58": "Direct Traffic",
  "59": "Escort or convoy / Security check",
  "60": "Squad in vicinity",
  "61": "Personnel in vicinity / Not wanted",
  "62": "Subject possibly wanted",
  "63": "Subject positive / Prepare to copy",
  "64": "Subject wanted / Found property",
  "65": "Net message assignment",
  "66": "Check officer's well-being",
  "67": "Clear for next message",
  "68": "Dispatch message",
  "69": "Clear to copy transmission?",
  "70": "Fire alarm / Prowler",
  "71": "Advise nature of fire / Shooting",
  "72": "Report progress of fire / Gun involved / D.O.A.",
  "73": "How do you copy / Smoke report",
  "74": "Negative / Theft",
  "75": "Severe weather statement",
  "76": "En route to location",
  "77": "Estimated Time of Arrival",
  "78": "Need assistance / Send ambulance",
  "79": "Notify coroner / Bomb threat",
  "80": "Pursuit in progress",
  "81": "Traffic stop initiated / Breathalyzer request",
  "82": "Reserve lodging",
  "83": "Work/school crossing detail",
  "84": "Advise ETA",
  "85": "Arrival delay due to [cause]",
  "86": "Officer on-duty",
  "87": "Give call letters of your station",
  "88": "Advise phone number of officer",
  "89": "Bomb threat",
  "90": "Alarm going off / Bank alarm",
  "91": "Pick up subject / Prepare for inspection / Animal",
  "92": "Subject in custody / Parking violation",
  "93": "Blockage",
  "94": "Street racing",
  "95": "Officer's residence",
  "96": "Mental patient / Detain suspect",
  "97": "Arrived at scene / Record information",
  "98": "Assignment complete / Prison break",
  "99": "Cardiac arrest / Officer held hostage",
  "100": "Misdemeanor warrant / Out using restroom",
  "101": "Ending security check",
  "102": "Cruelty to animals",
  "103": "Disturbance",
  "106": "Obscenity",
  "107": "Suspicious person",
  "108": "Officer down / Officer in danger",
  "109": "Suicide",
  "110": "Juvenile disturbance",
  "112": "Impersonating an officer",
  "200": "Narcotics, drugs involved",
  "1000": "Felony warrant / Dead person",
  "2000": "Police required immediately",
  "00": "Officer down, all patrols respond",
  "7b": "Out of service (personal)",
  "7c": "Out of service (court)",
  "7od": "Out of service (off duty)",
  "8ot": "In service (over time)",
  "15m": "Prisoner in custody (mental case)",
  "21a": "Advise home I will return at [ETA]",
  "21b": "Call your home",
  "29a": "Check wants, subject [PIN]",
  "29c": "Check complete, subject [NCIC]",
  "29f": "Subject wanted, felony",
  "29h": "Hazard potential from subject",
  "29m": "Subject wanted, misdemeanor",
  "29r": "Check wants and record, subject [PIN, CJIC]",
  "29v": "Vehicle wanted",
  "45a": "Condition of patient - Good",
  "45b": "Condition of patient - Serious",
  "45c": "Condition of patient - Critical",
  "45d": "Condition of patient - Dead",
  "54d": "Possible dead body",
  "55d": "Send coroner",
  "56a": "Suicide attempt",
  "80a": "Assist radio dispatcher",
  "91a": "Animal - stray",
  "91b": "Animal - noisy",
  "91c": "Animal - injured",
  "91d": "Animal - dead",
  "91e": "Animal - bite",
  "91g": "Animal - pickup",
  "91j": "Animal - pickup collect",
  "91l": "Animal - leash law violation",
  "91v": "Animal - vicious",
  "103f": "Disturbance by fight",
  "103m": "Disturbance by mental person"
};
